config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  resources :organizations do
    resources :callees, only: %i[new create edit update destroy]
  end

  resources :callees, only: %i[show] do
    resources :relationships, only: %i[create]
    resources :calls, only: %i[create]
  end # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :relationships, only: %i[index new]

  get '/pages/*id' => 'pages#show', as: :page, format: false

  get 'rules' => 'rules#index'
  post 'rules/accept' => 'rules#accept'

  post 'twilio/incoming' => 'twilio#incoming'
  post 'twilio/got_code' => 'twilio#got_code'
  post 'twilio/post_call' => 'twilio#post_call'
end

app/models/callee.rb
class Callee < ApplicationRecord
  belongs_to :organization
  has_many :relationships
  has_many :users, through: :relationships
  has_many :calls
  validates :phone_number, phone: { allow_blank: true, extensions: false }

  RELATIONSHIP_LIMIT = 1

  def available_relationships
    RELATIONSHIP_LIMIT - relationships.count
  end

  def can_start_relationship?
    available_relationships > 0
  end

  def e164_number
    number =
      phone_number.empty? ? organization.switchboard_number : phone_number
    Phonelib.parse(number).e164
  end
end

app/controllers/callees_controller.rb
class CalleesController < ApplicationController
  before_action :set_callee, only: %i[show edit update destroy]

  # GET /callees
  # GET /callees.json
  def index
    authorize Callee
    unless current_user.student?
      flash.alert = 'Not authorized.'
      redirect_to root_path
    end
    @callees = policy_scope(Callee)
  end

  # GET /callees/1
  # GET /callees/1.json
  def show
    @relationship = Relationship.find_by(callee: @callee, user: current_user)
    @relationship.ensure_code!
    @call_number = ENV['TWILIO_NUMBER']
  end

  # GET /callees/new
  def new
    @callee = Callee.new
    @callee.organization = Organization.find(params[:organization_id])
    authorize @callee
  end

  # GET /callees/1/edit
  def edit; end

  # POST /callees
  # POST /callees.json
  def create
    @callee = Callee.new(callee_params)
    @callee.organization = Organization.find(params[:organization_id])
    authorize @callee

    respond_to do |format|
      if @callee.save
        format.html do
          redirect_to @callee.organization,
                      notice: 'Callee was successfully created.'
        end
        format.json { render :show, status: :created, location: @callee }
      else
        format.html { render :new }
        format.json do
          render json: @callee.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /callees/1
  # PATCH/PUT /callees/1.json
  def update
    respond_to do |format|
      if @callee.update(callee_params)
        format.html do
          redirect_to @callee.organization,
                      notice: 'Callee was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @callee }
      else
        format.html { render :edit }
        format.json do
          render json: @callee.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /callees/1
  # DELETE /callees/1.json
  def destroy
    @callee.destroy
    respond_to do |format|
      format.html do
        redirect_to @callee.organization,
                    notice: 'Callee was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private # Use callbacks to share common setup or constraints between actions.
  def set_callee
    @callee = Callee.find(params[:id])
    authorize @callee
  end

  # Only allow a list of trusted parameters through.
  def callee_params
    params.require(:callee).permit(:name, :bio, :phone_number)
  end
end

app/helpers/callees_helper.rb
module CalleesHelper; end

app/views/callees/_form.html.erb
<%= form_with(model: [callee.organization, callee], local: true) do |form| %>
  <% if callee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(callee.errors.count, "error") %> prohibited this callee from being saved:</h2>

      <ul>
        <% callee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <p>
      This name will be visible to volunteers that choose to call this person.
      You may prefer to enter something such as "J. Doe" to preserve privacy.
    </p>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/callees/edit.html.erb
<h1>Editing Callee</h1>

<%= render 'form', callee: @callee %>

<%= link_to 'Back', @callee.organization %>

app/views/callees/new.html.erb
<h1>New Callee</h1>

<%= render 'form', callee: @callee %>

<%= link_to 'Back', organization_path(@callee.organization) %>

app/views/callees/show.html.erb
<h1><%= @callee.name %></h1>

<p>
  <%= @callee.bio %>
</p>

<h2>Call this person</h2>
<div class="call-info">
  <div class="text">Call</div>
  <div class="number"><%= Phonelib.parse(@call_number).national %></div>
  <div class="text">and enter the code</div>
  <div class="number"><%= @relationship.code %></div>
</div>

<% if @relationship.calls.any? %>
  <h2>Your previous calls</h2>
  <ul>
    <% @relationship.calls.each do |c| %>
      <li><%= local_time(c.call_date) %> - <%= c.complete? ? format_duration(c.seconds) : "call ongoing" %></li>
    <% end %>
  </ul>
  <p>Total: <%= format_duration(@relationship.calls.sum(:seconds)) %></p>
<% end %>

<%= link_to 'Back', relationships_path %>