config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  resources :organizations do
    resources :callees, only: %i[new create edit update destroy]
  end

  resources :callees, only: %i[show] do
    resources :relationships, only: %i[create]
    resources :calls, only: %i[create]
  end # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :relationships, only: %i[index new]

  get '/pages/*id' => 'pages#show', as: :page, format: false

  get 'rules' => 'rules#index'
  post 'rules/accept' => 'rules#accept'

  post 'twilio/incoming' => 'twilio#incoming'
  post 'twilio/got_code' => 'twilio#got_code'
  post 'twilio/post_call' => 'twilio#post_call'
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :callee

  def ensure_code!
    update(code: rand(100_000..999_999).to_s) unless code
  end

  def calls
    Call.where(user: user, callee: callee).order(call_date: :desc)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :check_rules

  def index
    skip_policy_scope
    authorize Relationship

    @callees = current_user.callees
    redirect_to new_relationship_path if @callees.empty?
  end

  def new
    authorize Relationship

    @callees = policy_scope(Callee) # TODO: limit to available folks in the query, not in code
    @callees = @callees.select &:can_start_relationship?
  end

  def create
    callee = Callee.find(params[:callee_id])
    @relationship = Relationship.new(callee: callee, user: current_user)
    authorize @relationship

    @relationship.save!
    redirect_to callee_path(callee)
  end

  protected

  def check_rules
    unless current_user.accepted_rules?
      skip_authorization
      skip_policy_scope
      redirect_to rules_path
    end
  end
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/views/relationships/index.html.erb
<% @callees.each do |callee| %>
  <div class="callee">
    <h2><%= link_to callee.name, callee_path(callee) %></h2>
    <p><%= callee.bio %></p>
    <p><%= link_to "Call", callee_path(callee)%> </p>
  </div>
<% end %>

<p>
  <% if current_user.can_start_relationship? %>
    <%= link_to "Call someone new", new_relationship_path %>
  <% else %>
    For safety reasons, we have a limit on how many people a volunteer can talk
    to. You've reached that limit, but you're more than welcome to continue
    calling the people you've already added!
  <% end %>
</p>

app/views/relationships/new.html.erb
<h1>
  <% if current_user.callees.empty? %>
    Choose someone to call
  <% else %>
    Call someone new
  <% end %>
</h1>

<% @callees.each do |callee| %>
  <% if callee.can_start_relationship? %>
    <div class="callee">
      <p><%= callee.bio %></p>
      <p><%= link_to "Select this person", callee_relationships_path(callee), method: :POST, data: {confirm: "Are you sure you'd like to add this person? You can add #{current_user.available_relationships} more people, including this one."} %></p>
    </div>
  <% end %>
<% end %>