config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  resources :organizations do
    resources :callees, only: %i[new create edit update destroy]
  end

  resources :callees, only: %i[show] do
    resources :relationships, only: %i[create]
    resources :calls, only: %i[create]
  end # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :relationships, only: %i[index new]

  get '/pages/*id' => 'pages#show', as: :page, format: false

  get 'rules' => 'rules#index'
  post 'rules/accept' => 'rules#accept'

  post 'twilio/incoming' => 'twilio#incoming'
  post 'twilio/got_code' => 'twilio#got_code'
  post 'twilio/post_call' => 'twilio#post_call'
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :callees
  has_many :organization_memberships
  has_many :users, through: :organization_memberships

  validates :switchboard_number, phone: { allow_blank: true, extensions: false }
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    authorize Organization
    @organizations = policy_scope Organization
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    authorize @organization
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    authorize @organization
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    authorize @organization

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
      authorize @organization
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:name, :switchboard_number)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :switchboard_number %>
    <%= form.text_field :switchboard_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<% if current_user.admin? %>
  <%
  total_students = User.where.not(confirmed_at: nil).count &:student?
  students_with_calls = User.joins(:calls).distinct.count
  %>
  <p>
    Total student volunteers: <%= total_students %> <br>
    Students who've made calls: <%= students_with_calls %> <br>
    Students who haven't made calls: <%= total_students - students_with_calls %>
  </p>

  <%
  callees_with_calls = Callee.joins(:calls).distinct.count
  %>
  <p>
    Total seniors: <%= Callee.count %> <br>
    Seniors who've gotten calls: <%= callees_with_calls %> <br>
    Seniors who haven't gotten calls: <%= Callee.count - callees_with_calls %>
  </p>

  <p>
    Total calls (over five minutes): <%= Call.where("seconds > 300").count %> <br>
    Total call time: <%= format_duration(Call.sum(:seconds)) %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Switchboard number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.switchboard_number %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Delete', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<h1> <%= @organization.name %> </h1>

<p>
  <strong>Switchboard number:</strong>
  <%= @organization.switchboard_number %>
</p>

<p>
  <h2>Staff</h2>
  <ul>
    <% @organization.users.each do |user| %>
      <li> <%= user.name %> (<%= user.email %>) </li>
    <% end %>
  </ul>
</p>

<h2>Callees</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @organization.callees.each do |callee| %>
      <tr>
        <td><%= callee.name %></td>
        <td><%= callee.bio %></td>
        <td><%= link_to 'Edit', edit_organization_callee_path(callee.organization, callee) %></td>
        <td><%= link_to 'Delete', [callee.organization, callee], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Callee', new_organization_callee_path(@organization) %>

<br>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>